use crate::criterion_results::BenchResult;
use crate::host::HostCapabilities;
use std::collections::BTreeMap;

#[derive(PartialEq, PartialOrd)]
enum ParamValue {
    Numeric(f64),
    String(String),
    None,
}

impl Eq for ParamValue {}
impl Ord for ParamValue {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.partial_cmp(other).unwrap_or(std::cmp::Ordering::Equal)
    }
}

fn parse_param(value_str: Option<&str>) -> ParamValue {
    let s = match value_str {
        Some(val) => val,
        None => return ParamValue::None,
    };
    for prefix in ["density_", "sparsity_"] {
        if let Some(pct) = s.strip_prefix(prefix) {
            if let Some(num) = pct.strip_suffix("pct") {
                if let Ok(n) = num.parse::<f64>() {
                    return ParamValue::Numeric(n);
                }
            }
        }
    }
    s.parse::<f64>()
        .map(ParamValue::Numeric)
        .unwrap_or_else(|_| ParamValue::String(s.to_string()))
}

fn format_time(ns: f64) -> String {
    if ns < 1.0 {
        format!("{:.2} ps", ns * 1000.0)
    } else if ns < 1000.0 {
        format!("{:.2} ns", ns)
    } else if ns < 1_000_000.0 {
        format!("{:.2} \u{03bc}s", ns / 1000.0)
    } else if ns < 1_000_000_000.0 {
        format!("{:.2} ms", ns / 1_000_000.0)
    } else {
        format!("{:.2} s", ns / 1_000_000_000.0)
    }
}

fn format_throughput(kind: &str, count: u64, ns: f64) -> String {
    let secs = ns / 1_000_000_000.0;
    if secs <= 0.0 {
        return "N/A".to_string();
    }
    let speed = count as f64 / secs;
    match kind {
        "Elements" if speed >= 1_000_000_000.0 => {
            format!("{:.3} Gelem/s", speed / 1_000_000_000.0)
        }
        "Elements" if speed >= 1_000_000.0 => {
            format!("{:.3} Melem/s", speed / 1_000_000.0)
        }
        "Elements" => format!("{:.3} Elem/s", speed),
        "Bytes" if speed >= 1_000_000_000.0 => {
            format!("{:.3} GB/s", speed / 1_000_000_000.0)
        }
        "Bytes" if speed >= 1_000_000.0 => format!("{:.3} MB/s", speed / 1_000_000.0),
        "Bytes" => format!("{:.3} B/s", speed),
        other => format!("{:.3} {other}/s", speed),
    }
}

pub(crate) fn render_markdown(
    results: &[BenchResult],
    cpu: &str,
    capabilities: HostCapabilities,
    generated_at: &str,
) -> String {
    let mut groups: BTreeMap<String, Vec<BenchResult>> = BTreeMap::new();
    for res in results {
        groups
            .entry(res.group_id.clone())
            .or_default()
            .push(res.clone());
    }

    let mut markdown = String::new();
    markdown.push_str("# Hermes SIMD Benchmark Results\n\n");
    markdown.push_str(&format!("- **CPU**: {cpu}\n"));
    markdown.push_str(&format!(
        "- **Runtime backend selected by dense dispatch**: `{}`\n",
        capabilities.runtime_backend()
    ));
    markdown.push_str(&format!(
        "- **Detected benchmark-relevant ISA features**: {}\n",
        capabilities.format_markdown()
    ));
    markdown.push_str(&format!("- **Date**: {generated_at}\n\n"));
    markdown.push_str("This file is dynamically generated by the benchmark runner. Performance values represent point estimates computed by Criterion. ISA-specific rows only validate features detected on this host; unsupported AVX-512/AMX paths require a matching runner.\n\n");

    for (group_name, mut items) in groups {
        render_group(&mut markdown, &group_name, &mut items);
    }
    while markdown.ends_with("\n\n") {
        markdown.pop();
    }
    markdown
}

fn render_group(markdown: &mut String, group_name: &str, items: &mut [BenchResult]) {
    markdown.push_str(&format!("## {group_name}\n\n"));
    items.sort_by(|a, b| {
        let a_param = parse_param(a.value_str.as_deref());
        let b_param = parse_param(b.value_str.as_deref());
        match a_param.cmp(&b_param) {
            std::cmp::Ordering::Equal => a.function_id.cmp(&b.function_id),
            other => other,
        }
    });

    let has_params = items.iter().any(|item| item.value_str.is_some());
    let group_wide_baseline = group_wide_baseline(items);
    let baselines = parameter_baselines(items, group_wide_baseline.is_some());
    let has_speedup = group_wide_baseline.is_some() || !baselines.is_empty();
    render_header(markdown, has_params, has_speedup);

    for item in items {
        render_row(
            markdown,
            item,
            has_params,
            has_speedup,
            group_wide_baseline.as_ref(),
            &baselines,
        );
    }
    markdown.push('\n');
}

fn render_header(markdown: &mut String, has_params: bool, has_speedup: bool) {
    match (has_params, has_speedup) {
        (true, true) => {
            markdown
                .push_str("| Function | Parameter | Time | Throughput | Speedup vs Baseline |\n");
            markdown.push_str("|---|---|---|---|---|\n");
        }
        (true, false) => {
            markdown.push_str("| Function | Parameter | Time | Throughput |\n");
            markdown.push_str("|---|---|---|---|\n");
        }
        (false, true) => {
            markdown.push_str("| Function | Time | Throughput | Speedup vs Baseline |\n");
            markdown.push_str("|---|---|---|---|\n");
        }
        (false, false) => {
            markdown.push_str("| Function | Time | Throughput |\n");
            markdown.push_str("|---|---|---|\n");
        }
    }
}

fn render_row(
    markdown: &mut String,
    item: &BenchResult,
    has_params: bool,
    has_speedup: bool,
    group_wide_baseline: Option<&BenchResult>,
    baselines: &BTreeMap<String, BenchResult>,
) {
    let time_formatted = format_time(item.time_ns);
    let throughput_formatted = match (&item.throughput_kind, item.throughput_val) {
        (Some(kind), Some(val)) => format_throughput(kind, val, item.time_ns),
        _ => "N/A".to_string(),
    };
    let speedup_str = speedup_string(item, group_wide_baseline, baselines);

    match (has_params, has_speedup) {
        (true, true) => markdown.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            item.function_id,
            item.value_str.as_deref().unwrap_or("-"),
            time_formatted,
            throughput_formatted,
            speedup_str
        )),
        (true, false) => markdown.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            item.function_id,
            item.value_str.as_deref().unwrap_or("-"),
            time_formatted,
            throughput_formatted
        )),
        (false, true) => markdown.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            item.function_id, time_formatted, throughput_formatted, speedup_str
        )),
        (false, false) => markdown.push_str(&format!(
            "| {} | {} | {} |\n",
            item.function_id, time_formatted, throughput_formatted
        )),
    }
}

fn speedup_string(
    item: &BenchResult,
    group_wide_baseline: Option<&BenchResult>,
    baselines: &BTreeMap<String, BenchResult>,
) -> String {
    let param_key = item.value_str.clone().unwrap_or_else(|| "none".to_string());
    if let Some(base_item) = group_wide_baseline {
        return speedup_against(item, base_item);
    }
    baselines
        .get(&param_key)
        .map_or_else(|| "-".to_string(), |base| speedup_against(item, base))
}

fn speedup_against(item: &BenchResult, base_item: &BenchResult) -> String {
    if item.function_id == base_item.function_id {
        format!("1.00x (Baseline: {})", base_item.function_id)
    } else {
        format!("{:.2}x", base_item.time_ns / item.time_ns)
    }
}

fn group_wide_baseline(items: &[BenchResult]) -> Option<BenchResult> {
    let mut baseline = None;
    for item in items {
        if is_baseline_candidate(&item.function_id)
            && item.value_str.is_none()
            && baseline.as_ref().is_none_or(|existing: &BenchResult| {
                existing.function_id != "scalar_iter" && item.function_id == "scalar_iter"
            })
        {
            baseline = Some(item.clone());
        }
    }
    baseline
}

fn parameter_baselines(
    items: &[BenchResult],
    has_group_wide_baseline: bool,
) -> BTreeMap<String, BenchResult> {
    let mut baselines: BTreeMap<String, BenchResult> = BTreeMap::new();
    if has_group_wide_baseline {
        return baselines;
    }
    for item in items {
        let param_key = item.value_str.clone().unwrap_or_else(|| "none".to_string());
        if is_baseline_candidate(&item.function_id)
            && baselines.get(&param_key).is_none_or(|existing| {
                existing.function_id != "scalar_iter" && item.function_id == "scalar_iter"
            })
        {
            baselines.insert(param_key, item.clone());
        }
    }
    baselines
}

fn is_baseline_candidate(function_id: &str) -> bool {
    matches!(
        function_id,
        "scalar_iter" | "dense_sum" | "dense_dot" | "dense_masked" | "dense" | "dispatch"
    )
}

#[cfg(test)]
mod tests {
    use super::{format_throughput, parse_param, ParamValue};

    #[test]
    fn parses_density_and_sparsity_parameters_as_numbers() {
        assert!(matches!(
            parse_param(Some("density_10pct")),
            ParamValue::Numeric(10.0)
        ));
        assert!(matches!(
            parse_param(Some("sparsity_99pct")),
            ParamValue::Numeric(99.0)
        ));
    }

    #[test]
    fn formats_byte_throughput() {
        assert_eq!(format_throughput("Bytes", 1_000, 1_000.0), "1.000 GB/s");
    }
}
