[package]
name = "hermes-simd-examples"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
publish = false

[dependencies]
hermes-simd = { path = "../hermes-simd", version = "0.4.0" }

[[example]]
name = "dot_product"
path = "examples/dot_product.rs"

[[example]]
name = "cow_example"
path = "examples/cow_example.rs"

[[example]]
name = "complex_dot"
path = "examples/complex_dot.rs"

[features]
default = ["mnemosyne-memory"]
mnemosyne-memory = ["hermes-simd/mnemosyne-memory"]
