[package]
name = "hermes-simd-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
hermes-numeric = { path = "../hermes-numeric" }
half = { workspace = true }
bytemuck = { version = "1.14", features = ["derive"] }
rkyv = { version = "0.7" }

[dev-dependencies]
hermes-simd-intrinsics = { path = "../hermes-simd-intrinsics" }

[lib]
doctest = false

