//! Generic interleaved complex kernels.
//!
//! The public surface accepts primitive lane slices in `[re, im, ...]` order so
//! domain crates can use their own complex storage types without Hermes taking a
//! dependency on a concrete complex-number crate.
//!
//! Arithmetic stays in vector registers for every `(T, Arch)` pair via the
//! adjacent-pair shuffle and alternating-FMA primitives on
//! [`SimdKernel`]:
//!
//! - `a * b`       = `fmaddsub(dup_even(a), b, mul(dup_odd(a), swap_adjacent(b)))`
//! - `a * conj(b)` = `fmsubadd(dup_odd(a), swap_adjacent(b), mul(dup_even(a), b))`
//!
//! Runtime architecture selection is generated by `#[runtime_dispatch]`, the
//! same mechanism used by the dense kernels — no per-type provider impls and no
//! `OnceLock` feature caching.

use hermes_simd_core::{arch::SimdArch, kernel::SimdKernel, scalar::Scalar, view::SimdError};
use hermes_simd_macros::runtime_dispatch;

const MAX_STACK_LANES: usize = 128;

#[inline]
fn mul_pair<T, const CONJ_B: bool>(ar: T, ai: T, br: T, bi: T) -> (T, T)
where
    T: Scalar,
{
    let bi = if CONJ_B { -bi } else { bi };
    (ar * br - ai * bi, ar * bi + ai * br)
}

/// Computes one register of interleaved complex products: `a[k] * b[k]`
/// (or `a[k] * conj(b[k])` when `CONJ_B`) over adjacent lane pairs.
///
/// # Safety
/// Processor must support the target features required by `A`.
#[inline(always)]
unsafe fn complex_mul_vector<T, A, const CONJ_B: bool>(av: A::Vector, bv: A::Vector) -> A::Vector
where
    T: Scalar,
    A: SimdArch + SimdKernel<T>,
{
    let b_sw = A::swap_adjacent(bv);
    if CONJ_B {
        // even: ai*bi + ar*br = re ; odd: ai*br - ar*bi = im
        A::fmsubadd(A::dup_odd(av), b_sw, A::mul(A::dup_even(av), bv))
    } else {
        // even: ar*br - ai*bi = re ; odd: ar*bi + ai*br = im
        A::fmaddsub(A::dup_even(av), bv, A::mul(A::dup_odd(av), b_sw))
    }
}

/// Multiplies interleaved complex values in-place using architecture `A`.
///
/// `a` and `b` must have identical even lengths. The operation is value
/// preserving with respect to scalar complex multiplication over adjacent
/// primitive lane pairs:
///
/// `a[k] = a[k] * b[k]` when `CONJ_B == false`, and
/// `a[k] = a[k] * conj(b[k])` when `CONJ_B == true`.
#[inline]
pub fn interleaved_complex_mul_assign<T, A, const CONJ_B: bool>(
    a: &mut [T],
    b: &[T],
) -> Result<(), SimdError>
where
    T: Scalar,
    A: SimdArch + SimdKernel<T>,
{
    if a.len() != b.len() || (a.len() & 1) != 0 {
        return Err(SimdError::LengthMismatch);
    }

    let lanes = A::LANE_COUNT;
    let mut offset = 0usize;

    // The vectorized path requires an even lane count so every register holds
    // whole (re, im) pairs; all provided backends satisfy this.
    if lanes >= 2 && lanes & 1 == 0 {
        while offset + lanes <= a.len() {
            // SAFETY: offset + lanes <= len was checked above; `a` and `b` are
            // valid for reads (and `a` for writes) of `lanes` primitive values.
            // `A`'s target features are guaranteed by the dispatching caller.
            unsafe {
                let av = A::load_unaligned(a.as_ptr().add(offset));
                let bv = A::load_unaligned(b.as_ptr().add(offset));
                let res = complex_mul_vector::<T, A, CONJ_B>(av, bv);
                A::store_unaligned(a.as_mut_ptr().add(offset), res);
            }
            offset += lanes;
        }
    }

    let mut lane = offset;
    while lane < a.len() {
        let (re, im) = mul_pair::<T, CONJ_B>(a[lane], a[lane + 1], b[lane], b[lane + 1]);
        a[lane] = re;
        a[lane + 1] = im;
        lane += 2;
    }

    Ok(())
}

/// Computes an interleaved complex dot product using architecture `A`.
///
/// Inputs must have identical even lengths in `[re0, im0, re1, im1, ...]`
/// primitive lane order. The returned tuple is `(re, im)` for
/// `sum(a[k] * b[k])`; when `CONJ_B` is true, the operation is
/// `sum(a[k] * conj(b[k]))`.
#[inline]
pub fn interleaved_complex_dot<T, A, const CONJ_B: bool>(
    a: &[T],
    b: &[T],
) -> Result<(T, T), SimdError>
where
    T: Scalar,
    A: SimdArch + SimdKernel<T>,
{
    if a.len() != b.len() || (a.len() & 1) != 0 {
        return Err(SimdError::LengthMismatch);
    }

    let lanes = A::LANE_COUNT;
    let mut offset = 0usize;
    let mut re = T::ZERO;
    let mut im = T::ZERO;

    if lanes >= 2 && lanes & 1 == 0 && offset + lanes <= a.len() {
        assert!(
            lanes <= MAX_STACK_LANES,
            "SIMD lane count exceeds stack buffer"
        );
        // SAFETY: feature availability is guaranteed by the dispatching caller.
        let mut acc = unsafe { A::zero() };
        while offset + lanes <= a.len() {
            // SAFETY: offset + lanes <= len was checked above; `a` and `b` are
            // valid for reads of `lanes` primitive values.
            unsafe {
                let av = A::load_unaligned(a.as_ptr().add(offset));
                let bv = A::load_unaligned(b.as_ptr().add(offset));
                acc = A::add(acc, complex_mul_vector::<T, A, CONJ_B>(av, bv));
            }
            offset += lanes;
        }

        // Single spill: fold even lanes into re, odd lanes into im.
        let mut buf = [T::ZERO; MAX_STACK_LANES];
        // SAFETY: buf holds at least `lanes` elements (asserted above).
        unsafe { A::store_unaligned(buf.as_mut_ptr(), acc) };
        let mut lane = 0usize;
        while lane < lanes {
            re = re + buf[lane];
            im = im + buf[lane + 1];
            lane += 2;
        }
    }

    let mut lane = offset;
    while lane < a.len() {
        let (prod_re, prod_im) = mul_pair::<T, CONJ_B>(a[lane], a[lane + 1], b[lane], b[lane + 1]);
        re = re + prod_re;
        im = im + prod_im;
        lane += 2;
    }

    Ok((re, im))
}

#[runtime_dispatch(avx512f, avx2, neon, scalar)]
pub(super) fn dispatch_interleaved_complex_mul_assign_impl<T, const CONJ_B: bool, A>(
    a: &mut [T],
    b: &[T],
) -> Result<(), SimdError>
where
    T: Scalar,
    A: SimdArch + SimdKernel<T>,
{
    interleaved_complex_mul_assign::<T, A, CONJ_B>(a, b)
}

#[runtime_dispatch(avx512f, avx2, neon, scalar)]
pub(super) fn dispatch_interleaved_complex_dot_impl<T, const CONJ_B: bool, A>(
    a: &[T],
    b: &[T],
) -> Result<(T, T), SimdError>
where
    T: Scalar,
    A: SimdArch + SimdKernel<T>,
{
    interleaved_complex_dot::<T, A, CONJ_B>(a, b)
}
