[package]
name = "hermes-simd-intrinsics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
hermes-simd-core = { path = "../hermes-simd-core", version = "0.3.0" }
hermes-numeric = { path = "../hermes-numeric", version = "0.3.0", default-features = false }
half = { workspace = true }
bytemuck = { version = "1.14" }
rkyv = { version = "0.7" }

[features]
default = ["std", "parallel", "mnemosyne-memory"]
std = ["hermes-simd-core/std", "hermes-numeric/std"]
parallel = ["hermes-simd-core/parallel", "hermes-numeric/parallel"]
mnemosyne-memory = [
    "hermes-simd-core/mnemosyne-memory",
    "hermes-numeric/mnemosyne-memory",
]
