[package]
name = "hermes-simd-intrinsics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
hermes-simd-core = { path = "../hermes-simd-core", version = "0.6.0" }
eunomia = { workspace = true }

[features]
default = ["std", "mnemosyne-memory"]
std = ["hermes-simd-core/std", "eunomia/std"]
mnemosyne-memory = ["hermes-simd-core/mnemosyne-memory"]
