#!/usr/bin/env python3
"""Generate or verify the Architecture Decision Record index."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parent.parent
ADR_DIRECTORY = REPOSITORY / "docs" / "adr"
INDEX = ADR_DIRECTORY / "README.md"

TITLE_PATTERNS = (
    re.compile(r"^# ADR (?P<number>\d{3,4}): (?P<title>.+)$", re.MULTILINE),
    re.compile(r"^# (?P<number>\d{3,4}) — (?P<title>.+)$", re.MULTILINE),
)
NUMBERED = re.compile(r"\d{3,4}-.*\.md")
INLINE_STATUS = re.compile(
    r"^-\s+(?:\*\*Status:\*\*|Status:)\s+(?P<status>Proposed|Accepted|Rejected)\b",
    re.MULTILINE,
)
SECTION_STATUS = re.compile(
    r"^## Status\s*$\s*^(?P<status>Proposed|Accepted|Rejected)\b",
    re.MULTILINE,
)


@dataclass(frozen=True)
class Adr:
    """One validated ADR index entry."""

    number: str
    title: str
    status: str
    filename: str


def parse_adr(path: Path) -> Adr:
    """Parse and validate one ADR's number, title, and canonical status."""
    text = path.read_text(encoding="utf-8")
    heading = None
    for pattern in TITLE_PATTERNS:
        heading = pattern.search(text)
        if heading is not None:
            break
    if heading is None:
        raise ValueError(f"{path.name}: missing canonical ADR heading")

    number = heading.group("number")
    # The numeric prefix at whatever width this repository uses; NUMBERED has
    # already guaranteed three or four digits followed by a dash.
    filename_number = path.name.split("-", 1)[0]
    if filename_number != number:
        raise ValueError(
            f"{path.name}: heading number {number} does not match filename {filename_number}"
        )

    status_match = INLINE_STATUS.search(text) or SECTION_STATUS.search(text)
    if status_match is None:
        raise ValueError(f"{path.name}: missing Proposed, Accepted, or Rejected status")

    return Adr(number, heading.group("title").strip(), status_match.group("status"), path.name)


def render() -> str:
    """Render the complete deterministic ADR index."""
    entries = [
        parse_adr(path)
        # Three- or four-digit numbering: repositories differ, the generator
        # does not. The width is whatever each repository already uses.
        for path in sorted(
            path
            for path in ADR_DIRECTORY.glob("[0-9]*-*.md")
            if NUMBERED.fullmatch(path.name)
        )
    ]
    numbers = [entry.number for entry in entries]
    if len(numbers) != len(set(numbers)):
        raise ValueError("duplicate ADR numbers")

    lines = [
        "# ADR index",
        "",
        "<!-- Generated by scripts/adr-index.py — do not hand-edit.",
        "     Regenerate:  python scripts/adr-index.py generate",
        "     Check:       python scripts/adr-index.py check -->",
        "",
        "| ADR | Title | Status |",
        "| --- | ----- | ------ |",
    ]
    lines.extend(
        f"| [{entry.number}]({entry.filename}) | {entry.title} | {entry.status} |"
        for entry in entries
    )
    return "\n".join(lines) + "\n"


def check(expected: str) -> int:
    """Return success only when the committed index equals generated output."""
    actual = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
    if actual == expected:
        print(f"ADR index is current ({expected.count('| [')} records).")
        return 0

    sys.stderr.writelines(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(INDEX),
            tofile="generated ADR index",
        )
    )
    return 1


def main() -> int:
    """Run the selected index operation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("generate", "check"))
    arguments = parser.parse_args()

    try:
        generated = render()
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if arguments.mode == "generate":
        INDEX.write_text(generated, encoding="utf-8", newline="\n")
        print(f"ADR index generated ({generated.count('| [')} records).")
        return 0
    return check(generated)


if __name__ == "__main__":
    raise SystemExit(main())
