[package]
name = "hermes-simd"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
hermes-simd-core = { path = "../hermes-simd-core", default-features = false }
hermes-simd-intrinsics = { path = "../hermes-simd-intrinsics", default-features = false }
hermes-numeric = { path = "../hermes-numeric", default-features = false }
hermes-simd-macros = { path = "../hermes-simd-macros" }
hermes-simd-types = { path = "../hermes-simd-types", default-features = false }
half = { workspace = true }
bytemuck = { version = "1.14" }
rkyv = { version = "0.7" }

[dev-dependencies]
proptest = "1.4"

[features]
default = ["std"]
std = [
    "hermes-simd-core/std",
    "hermes-simd-intrinsics/std",
    "hermes-numeric/std",
    "hermes-simd-types/std",
]
