[package]
name = "hermes-simd-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Monomorphized vector register types for the hermes-simd workspace"

[dependencies]
hermes-simd-core = { path = "../hermes-simd-core", version = "0.5.0", default-features = false }
hermes-simd-intrinsics = { path = "../hermes-simd-intrinsics", version = "0.5.0", default-features = false }

[features]
default = ["std", "mnemosyne-memory"]
std = ["hermes-simd-core/std", "hermes-simd-intrinsics/std"]
mnemosyne-memory = [
    "hermes-simd-core/mnemosyne-memory",
    "hermes-simd-intrinsics/mnemosyne-memory",
]
